name: wgite_label_app
description: White-label application.

publish_to: 'none'

version: 1.1.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  cloud_firestore: ^1.0.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.4.1
  firebase_core: ^1.0.4
  flutter_linkify: ^5.0.2
  get: ^4.1.4
  google_fonts: ^2.0.0
  money_converter: ^0.0.4
  package_info_plus: ^1.0.1
  responsive_builder: ^0.4.1
  spaces: ^0.5.0
  url_launcher: ^6.0.6
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png
    - assets/img/linkedin_logo_white.png
    - assets/img/background.jpg
    - assets/img/analyzing.jpg
    - assets/img/planning.jpg
